[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "huggingface-hub[cli]>=0.29.3",
    "uvicorn[standard]>=0.34.0",
]
